# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "Getting started"
  link: "/getting-started"
- label: "Microsoft Office"
  items:
    - label: "Microsoft Word"
      link: "/msoffice/word"
    - label: "Microsoft Excel"
      link: "/msoffice/excel"
- label: "Chemdraw"
  items:
    - label: "Chemdraw"
      link: "/chemdraw/chemdraw"
- label: "Endnote"
  items:
    - label: "Introduction"
      link: "/endnote/introduction"
- label: 学习类
  items:
    - label: "有机化学"
      link: "/organic-chem/must-read"
- label: Machine Learning
  items:
    - label: "Neural Networks"
      link: "machine-learning/neural-network"
- label: Usage
  items:
    - label: "Creating docs"
      link: "/usage/creating-docs"
    - label: "Navigation"
      link: "/usage/navigation"
    - label: "Shadowing"
      link: "/usage/shadowing"
